### ISSUE TITLE
Frontend sends 'process' parameter while backend expects 'redirect_url' for login endpoint

### ISSUE THREAD

**Issue by leonjvr** [sartography/spiff-arena#2356]
There is a parameter name mismatch between the SpiffWorkflow frontend and backend when initiating the OAuth login flow. The frontend sends a `process` parameter while the backend expects a `redirect_url` parameter, causing authentication to fail with an "Invalid redirect url" error.

## Environment
- **SpiffWorkflow Backend**: ghcr.io/sartography/spiffworkflow-backend:latest (as of 2025-06-03)
- **SpiffWorkflow Frontend**: ghcr.io/sartography/spiffworkflow-frontend:latest (as of 2025-06-03)
- **Source Repository**: https://github.com/sartography/spiff-arena (monorepo)
- **Keycloak**: quay.io/keycloak/keycloak:23.0.7
- **Deployment Method**: Docker Compose
- **Authentication**: OpenID Connect with Keycloak

## Steps to Reproduce

1. Set up SpiffWorkflow using Docker Compose with the following configuration:
   ```yaml
   services:
     spiffworkflow-backend:
       image: ghcr.io/sartography/spiffworkflow-backend:latest
       environment:
         SPIFFWORKFLOW_BACKEND_OPEN_ID_SERVER_URL: http://keycloak:8080/realms/spiffworkflow
         SPIFFWORKFLOW_BACKEND_OPEN_ID_CLIENT_ID: spiffworkflow-client
         SPIFFWORKFLOW_BACKEND_URL_FOR_FRONTEND: http://localhost
         # ... other required environment variables

     spiffworkflow-frontend:
       image: ghcr.io/sartography/spiffworkflow-frontend:latest
       environment:
         SPIFFWORKFLOW_FRONTEND_RUNTIME_CONFIG_APP_ROUTING_STRATEGY: path_based
         # ... other environment variables

     keycloak:
       image: quay.io/keycloak/keycloak:23.0.7
       # ... keycloak configuration
   ```

2. Configure Keycloak with a realm and client for SpiffWorkflow
3. Access the frontend at http://localhost/
4. Navigate to a protected route (e.g., http://localhost/process-models)
5. Observe the authentication flow

## Expected Behavior
The frontend should redirect to Keycloak for authentication when accessing protected routes.

## Actual Behavior
The authentication fails with the following error in the backend logs:
```
InvalidRedirectUrlError: Invalid redirect url was given: '/'. It must start with the frontend url: 'http://localhost'
```

### Frontend Request
The frontend makes a login request with the following format:
```
GET /api/v1.0/login?authentication_identifier=default&process=/process-models
```

### Backend Expectation
The backend login function signature (from spiff-arena/spiffworkflow-backend/src/spiffworkflow_backend/routes/authentication_controller.py) expects:
```python
def login(
    authentication_identifier: str,
    redirect_url: str = "/",
    process_instance_id: int | None = None,
    task_guid: str | None = None,
) -> Response:
```

The backend expects a `redirect_url` parameter, not `process`.

### Evidence
When manually testing with the correct parameter name:
```bash
curl -X GET "http://localhost/api/v1.0/login?authentication_identifier=default&redirect_url=http://localhost/process-models"
```

The response is successful (302 redirect to Keycloak):
```
< HTTP/1.1 302 FOUND
< Location: http://localhost/auth/realms/spiffworkflow/protocol/openid-connect/auth?state=...&redirect_uri=...
```

## Impact
- Users cannot authenticate with SpiffWorkflow when using the standard Docker images
- The OIDC flow is broken out of the box
- Requires manual workarounds to fix

### Option 1: Update Frontend (Recommended)
Modify the frontend to use `redirect_url` parameter instead of `process` when calling the login endpoint.

### Option 2: Update Backend
Modify the backend to accept both `process` and `redirect_url` parameters for backward compatibility:
```python
def login(
    authentication_identifier: str,
    redirect_url: str = None,
    process: str = None,  # For backward compatibility
    process_instance_id: int | None = None,
    task_guid: str | None = None,
) -> Response:
    # Use redirect_url if provided, otherwise fall back to process
    final_redirect_url = redirect_url or process or "/"
    # ... rest of the function
```

### Option 3: Add Configuration
Add an environment variable to configure the parameter name, though this adds unnecessary complexity.

## Workaround
For those encountering this issue, a temporary workaround is to intercept and modify the API calls on the frontend. This can be done by injecting JavaScript that converts the `process` parameter to `redirect_url`:

```javascript
// Intercept fetch requests
const originalFetch = window.fetch;
window.fetch = function(url, options) {
    const urlString = url.toString();
    if (urlString.includes('/v1.0/login') && urlString.includes('process=')) {
        const urlObj = new URL(urlString);
        const processValue = urlObj.searchParams.get('process');
        if (processValue) {
            urlObj.searchParams.delete('process');
            const redirectUrl = processValue.startsWith('http') ? processValue : window.location.origin + processValue;
            urlObj.searchParams.set('redirect_url', redirectUrl);
            return originalFetch.call(this, urlObj.toString(), options);
        }
    }
    return originalFetch.call(this, url, options);
};
```

## Additional Context
- This issue appears to be a mismatch between frontend and backend development
- No configuration option was found to control this parameter name
- The issue prevents the standard Docker deployment from working without modifications

## Questions for Maintainers
1. Is the `process` parameter name intentional for a specific use case?
2. Are there different versions of frontend/backend that are compatible?
3. Should this be fixed in the frontend or backend?

---

**Note**: I've verified this issue with the latest Docker images as of 2025-06-03. Happy to provide additional logs or test proposed fixes.
